import Head from 'next/head';
import ListadoPersonajes from '../components/ListadoPersonajes';

export default function Home() {
  return (
    <div>
      <Head>
        <title>StarWars LQN</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        {/* <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" /> */}
      </Head>

      <ListadoPersonajes />
    </div>
  )
}
